### ISSUE TITLE
Testing pyrtstools & model

### ISSUE THREAD

**Issue by frankpreel** [linto-ai/pyrtstools#1]
I've checked out the current repo and modify the listenner.py file to match with my USB microphone.
```
        self._stream = self._audio.open(format=pyaudio.paInt16,
                                        channels=1,
                                        rate=44100,
                                        input_device_index=2,
                                        input=True,
                                        frames_per_buffer=1024)
```
I've checked out also the default model `https://github.com/linto-ai/linto-models` 
And tried out the pipeline detecting hotword sample app, configured with the repo above, with several tries (linto, hey linto, hello linto) but no hotword seems to be detected.

The microphone is functional (I can use arecord & aplay to recording and listening wav file).
My environment is : Raspbian GNU/Linux 10 (buster)

Can you please help, what wrong why this config?

**Comment by Lokhozt** [comment]
Make sure to match the model sampling rate which is 16000Hz in that case.

**Comment by frankpreel** [comment]
I've configured pulseaudio sound server, thus pyaudio in now able to use rate=16000 on my device.
But I still not notice any callback when saying the word 'LinTo' in my microphone.

**Comment by romilchaudhary** [comment]
Is this issue resolved? I'm facing the same issue

**Comment by romilchaudhary** [comment]
> I've configured pulseaudio sound server, thus pyaudio in now able to use rate=16000 on my device.
> But I still not notice any callback when saying the word 'LinTo' in my microphone.
Hi Frankpreel,
Is this issue resolved?

**Comment by frankpreel** [comment]
Yes, thanks for your support

**Comment by Lokhozt** [comment]
Sorry for the delay:
- Are you using the VAD ? I  noticed that VAD sometime doesn't work properly with some microphone ?
