### ISSUE TITLE
Feature amalgamation of FFT routines and optimisation.

### ISSUE THREAD

**Issue by StuartIanNaylor** [linto-ai/pyrtstools#3]
Just a question as what happened to https://github.com/linto-ai/gpu-ne10-mfcc?

Both VAD & Features use almost the same FFT functions and probably could be optimised into a single shareable lib.
The Libs are there and would greatly benefit from the Arm optimised routines for this.
https://projectne10.github.io/Ne10/

The WebRtcVad is likely pretty much C optimised but what happened to the great idea of optimised MFCC?
I read about https://medium.com/linagoralabs/computing-mfccs-voice-recognition-features-on-arm-systems-dae45f016eb6 and thought yeah great job done.
Maybe also add a parameter log-mel-amplitudes to a suitable power (around 2 or 3) before taking the DCT (noise reduction) with the bandpass filters and like.
But surely a C routine would be less load and much faster?
Arm actually did a lib for their microcontrollers
https://github.com/ARM-software/ML-KWS-for-MCU/tree/master/Deployment/Source/MFCC
But quite a few implementations exist if there where problems with the original code.
https://projectne10.github.io/Ne10/doc/group__groupDSPs.html
https://github.com/rohithkd/libmfcc
https://github.com/dspavankumar/compute-mfcc
https://github.com/r9y9/SPTK
https://github.com/tlacael/MFCC
https://github.com/JuliaDSP/MFCC.jl

Also it did occur to me that the commonility between VAD and MFCC is so strong that are they not both part of the same functional block and could share processing?
But maybe one of the above might be interested in contributing the last one JuliaDSP/MFCC.jl seems extremely comphrehensive.

**Comment by StuartIanNaylor** [comment]
PS after reading the read.me of https://github.com/JuliaDSP/MFCC.jl and https://labrosa.ee.columbia.edu/matlab/rastamat/ I really do suggest you take a look.

**Comment by Lokhozt** [comment]
Hello, i will look into it.

**Comment by StuartIanNaylor** [comment]
Cheers Lokhortz in terms of preference though I would rather have a https://projectne10.github.io/Ne10/doc/group__groupDSPs.html optimised Neon MFCC/VAD.

You can get approx a perf gain of 1.2 to 1.8 with the use of the above Neon libs and neon in general.

The JuliaDSP through choice and selection of best result science it provides huge scope and choice in how you provide and process MFCC.
Its an amazing lib and wow with HMG it would provide an amazing toolset but still I would go for less functionality but NEON optimised as Cortex A35/53 is still very cost effective.
Julia is supposedly extremely fast but presuming compared to specific Neon libs not as fast as it could be.

Also I have been wondering for some time that function of MFCC & VAD is so similar in operation that could not VAD be just a single sample step of the MFFC process or MFFC is just the output of a continoius VAD process.
Currently completely different libs and threads are basically running load heavy FFT but the same routine could provide VAD RMS and MFCC Feature collection?

I think this is what feacalc() does from JuliaDSP so its likely to be less load intensive than unessacary seperation of VAD & MFCC routines even when NEON optimised.
A NEON optimised combined VAD/MFCC Julia like lib is my ultimate wish list as from readind approx results and a bit of theory resultant load could be as low as 30% of the current process.

**Comment by Lokhozt** [comment]
When i have some time (Might not be right now) i will work on optimizing the libraries, keep in mind though that the library is not exclusively targeted on arm platforms.

**Comment by StuartIanNaylor** [comment]
Yeah I understand that and why also maybe just employment of the Julia lib might be an option as part of the performance gain is amalgamation of VAD & MFCC process which I think from reading they do.
For edge or my term for even lesser devices such as edge satelites 'shelf devices' that a common use is likely to be Arm though.
I don't no how interchangeable FFT3W and the Neon libs are but presume you could in the make.
In fact FFT3W is NEON optimised and not sure if the projectne10 libs have anywhere near the perf gains thier trumpet call sounds.
The Julia lib might run without NEON optimisation that is all I was saying.

Also @Lokhozt have a look at https://github.com/voice-engine/ec as works quite well Cortex A35/53 and above and often overlooked when a common action is media playing.
Alsa-plugins Speex Echo and Pulseaudio WebRtc Aec seem to fail for me and its been the only satisfactory software option.

My curiosity was why is the optimised neon lib you provided not been used as that obviously is rated highly as a desired need.
I was browsing through the libs and noticed it and because of it that highlighted the thought and direction you had given the project.
Then sort of confused on looking at the code that its not used?

All in your own time as its purely opinion and feedback, if you are developing maybe bear in mind some of the issues and options raised.

Thanks
